# Generated by Django 4.2.16 on 2024-10-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytig", "0002_produitavailable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitPoisson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("tigID", models.IntegerField(default="-1")),
            ],
            options={
                "ordering": ("tigID",),
            },
        ),
    ]
